public class LoopsInApex {
    
    public static void handleForLoops(){
        
        List <String> myCharacters = new List <string> {'Trainer', 'mentor', 'Student'};
            
            for(String myCharacterName : mycharacters){
                system.debug(myCharacterName);
            }
        Set<Id> myAccIds = new set<Id> {'001gL00000L46VoQAJ','001gL00000T1xmwQAB'};
        	
            for (Id eachAccId : myAccIds ){
                system.debug(eachAccId);
            }
        
    }

}